analytics.onpremise.enable=true
onpremise.email="katalon@qgamesidn.com"
onpremise.password="2PtalXNYuQLkGoshfPaIUA\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1634164,\\"accountUuid\\"\:\\"cb6f3d86-1372-44ee-aedc-af1d65e5b40b\\",\\"id\\"\:3138507,\\"name\\"\:\\"org_0122\\",\\"role\\"\:\\"OWNER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://testops.katalon.io"
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3101544,\\n  \\"name\\"\: \\"firstPrj\\",\\n  \\"teamId\\"\: 3073375,\\n  \\"organizationId\\"\: 3138507,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3073375\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
