<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>af2f7dac-541e-4e8f-b3e2-135214f3ebba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fdr-7d1cb9ce115e4d1c98f169e322b8ee65']/div/div/div/div/div/div/a/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sds-comps-base-layout.sds-comps-inline-layout.sds-comps-image.sds-comps-image-circle.fit-cover > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;www.knotz.co.kr&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87ec2fbc-1e35-45e0-86fd-776f47081760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>321932e5-9e06-410e-81ff-af854c77f1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>4cbd1253-9d43-4e78-9d37-30c2bf0f4bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1528ecb9-d251-430b-9867-994ce54a31c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://search.pstatic.net/sunny?src=https%3A%2F%2Fwww.knotz.co.kr%2Fimages%2Fknotz.ico&amp;type=f30_30_png_expire24</value>
      <webElementGuid>3aad4b68-234c-4afe-9f50-5f403ab7d312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdr-7d1cb9ce115e4d1c98f169e322b8ee65&quot;)/div[@class=&quot;xO4uAj8Zk__cJ7KE3VSh desktop_mode api_subject_bx fds-root-overflow-reset&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout fds-web-root&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout fds-web-list-root fds-web-list-vert-padding&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout fds-web-doc-root u7m3J4vzWxO7iY8XLfYR fds-web-normal-doc-root&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout cd1rAwZ_cJyjmoNwHHzM&quot;]/div[@class=&quot;sds-comps-horizontal-layout sds-comps-full-layout MjAqPA22QJ_GqBQ2a_Rf&quot;]/a[@class=&quot;fender-ui_228e3bd1 XCoe8pmPdXBrcS2sZqSp&quot;]/div[@class=&quot;sds-comps-horizontal-layout sds-comps-full-layout sds-comps-profile type-web size-lg title-color-g10&quot;]/div[@class=&quot;sds-comps-horizontal-layout sds-comps-inline-layout sds-comps-profile-source&quot;]/div[@class=&quot;sds-comps-horizontal-layout sds-comps-inline-layout sds-comps-profile-source-thumb&quot;]/div[@class=&quot;sds-comps-horizontal-layout sds-comps-inline-layout sds-comps-profile-thumbnail type-web size-lg&quot;]/div[@class=&quot;sds-comps-base-layout sds-comps-inline-layout sds-comps-image sds-comps-image-circle fit-cover&quot;]/img[1]</value>
      <webElementGuid>8a058c87-a98a-4522-aa74-98d825fee12e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fdr-7d1cb9ce115e4d1c98f169e322b8ee65']/div/div/div/div/div/div/a/div/div/div/div/div/img</value>
      <webElementGuid>a12e7a6e-8fb0-4764-91d3-7d8d558cd493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://search.pstatic.net/sunny?src=https%3A%2F%2Fwww.knotz.co.kr%2Fimages%2Fknotz.ico&amp;type=f30_30_png_expire24')]</value>
      <webElementGuid>9566e65b-11d8-4250-94d4-09b8312de4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>6106f982-3a1e-4d49-b3ff-1dacb459962d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://search.pstatic.net/sunny?src=https%3A%2F%2Fwww.knotz.co.kr%2Fimages%2Fknotz.ico&amp;type=f30_30_png_expire24']</value>
      <webElementGuid>75d593f4-3caf-4a2c-94ba-15472a8be4ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
