<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Keep_sds-comps-text sds-comps-text-ell_6500ae</name>
   <tag></tag>
   <elementGuidId>9d82808a-af0c-4807-843e-1db4f6448064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fdr-7d1cb9ce115e4d1c98f169e322b8ee65']/div/div/div/div/div/div[2]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1.sds-comps-text-type-headline1.sds-comps-text-weight-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;KNOTZ&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16faa6c9-2667-4748-89c5-e4b270a30083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm</value>
      <webElementGuid>38c29f25-d2fb-4fad-b5c7-08d60db73962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KNOTZ</value>
      <webElementGuid>1d605b3d-58ff-4335-bb7f-7aa67dd94865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdr-7d1cb9ce115e4d1c98f169e322b8ee65&quot;)/div[@class=&quot;xO4uAj8Zk__cJ7KE3VSh desktop_mode api_subject_bx fds-root-overflow-reset&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout fds-web-root&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout fds-web-list-root fds-web-list-vert-padding&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout fds-web-doc-root u7m3J4vzWxO7iY8XLfYR fds-web-normal-doc-root&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout cd1rAwZ_cJyjmoNwHHzM&quot;]/div[@class=&quot;sds-comps-vertical-layout sds-comps-full-layout Ukl66z6jz4M356vUKswK IJJ253XQkK71YdzYLqWd&quot;]/div[@class=&quot;sds-comps-horizontal-layout sds-comps-full-layout asFelSwcnsnCTHGlWxrb&quot;]/a[@class=&quot;fender-ui_228e3bd1 dJUZtGyi946615CxmehU&quot;]/span[@class=&quot;sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm&quot;]</value>
      <webElementGuid>8f3283b3-1c6d-4032-bb80-ccef78a4d0de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fdr-7d1cb9ce115e4d1c98f169e322b8ee65']/div/div/div/div/div/div[2]/div/a/span</value>
      <webElementGuid>7a028fa4-a7b3-400a-810a-c84643c6f06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep에 바로가기'])[1]/following::span[1]</value>
      <webElementGuid>23325b53-510b-4078-a640-7ac4462e2e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.knotz.co.kr'])[1]/following::span[1]</value>
      <webElementGuid>7a6c7f75-3308-4599-8710-000dc5d5a90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='회사소개'])[1]/preceding::span[1]</value>
      <webElementGuid>e8944073-a4ff-4645-92b5-d8ad5bf408da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/preceding::span[2]</value>
      <webElementGuid>e007a3c6-0417-45f2-8ceb-b652af826086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KNOTZ']/parent::*</value>
      <webElementGuid>ee0fce05-d3c0-4ffc-acec-475039ea1c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div[2]/div/a/span</value>
      <webElementGuid>c1e416c0-285a-442f-a403-641246c3d50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KNOTZ' or . = 'KNOTZ')]</value>
      <webElementGuid>49f1323c-b8bc-40a6-891f-57bd96a3165b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fdr-2b53f7a124494755aa1c67db59d04b87']/div/div/div/div/div/div[2]/div/a/span</value>
      <webElementGuid>6592ad63-fc1c-4d13-8824-e1b4a7005e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
